#2.3ReformPythonDraw.py
import turtle
turtle.setup(650,350,200,200)
turtle.penup()
turtle.fd(-250)
turtle.pendown()
turtle.pensize(25)
turtle.seth(-40)
def drawTurtle():
    turtle.circle(40,80)
    turtle.circle(-40,80)
turtle.pencolor("red")
drawTurtle()
turtle.pencolor("green")
drawTurtle()
turtle.pencolor("blue")
drawTurtle()
turtle.pencolor("yellow")
drawTurtle()
turtle.pencolor("purple")
turtle.circle(40,80/2)
turtle.fd(40)
turtle.circle(16,180)
turtle.fd(40*2/3)
turtle.done()
